### ISSUE TITLE
Package Scripts Order

### ISSUE THREAD

**Issue by reggi** [keithamus/sort-package-json#19]
In my "scripts" I am seeing this order: 

```
    "test": "jest",
    "posttest": "npm run lint",
    "test:update": "jest -u"
```

Why isn't this alphabetical?

**Comment by keithamus** [comment]
Hey @reggi thanks for the issue.

`post*` and `pre*` scripts have specific meaning for `package.json` - `posttest` in this case will run after `test` automatically. Because of this, it felt more intuitive to sort these not by alphabetical order, but to specifically order `pre*` scripts before `*` and `post*` scripts after `*`.

I'll close this because I think we're doing the right thing here. If you want to discuss it more we can, and I can always re-open the issue.

**Comment by waldyrious** [comment]
For future reference, this behavior has changed slightly in #49: now, the "pre" and "post" prefixes will only be treated specially if they're not followed by a `-` character (e.g. `pre-foo` won't be sorted at the start, while `prefoo` will).
