### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by muuvmuuv** [keithamus/sort-package-json#47]
Wouldn't it be great to have a config stored in the `~/.config/sortpackagerc.json` where users can add additional configuration like there own order? More likely because some things are not supported yet and placed at the bottom we could let the user set his own priority so it is in his satisfaction. After we publish a official support for a key he set manually we could notify him to delete it or discuss with us about the priority level.

What do you think?

**Comment by keithamus** [comment]
Thanks for the issue @muuvmuuv 

There's been some discussion about this in other issues. See for example #30, and https://github.com/keithamus/sort-package-json/issues/39#issuecomment-401353234 

> Let's keep in mind the intent behind sorting a package.json is to keep it readable - to keep things in predictable places, so I as a developer can move from one package to the next, and read through the package.json knowing "dependencies goes below scripts". If all of a sudden someone out there decides to create a custom config to sort scripts below dependencies - well, the contract is broken, suddenly the intent of the tool is invalidated, and you may as well not run it at all.


I'm going to close this because I _dont_ think it would be great to have this tool be configurable. If you disagree, I encourage you to fork this package, I'm also happy to make any code changes here that could make a fork easier to work with.
