### ISSUE TITLE
idea: sort packages by npm documentation order and then custom properties

### ISSUE THREAD

**Issue by amilajack** [keithamus/sort-package-json#56]
The [npm documentation for package.json fields](https://docs.npmjs.com/files/package.json) seems to list the properties of the package.json from most used to least used. I makes sense to me that we should sort by using the same order that the properties are listed in in the docs and then append custom properties (`jest`, '`eslintConfig', etc). Thoughts?

**Comment by keithamus** [comment]
This is mostly the case, the caveat being that custom properties for configs are listed above dependencies, because dependencies can get quite large so we don't want to have too much scrolling happening. I also quite like the side effect that dependencies are sorted to almost at the bottom of a package.json so I can just scroll to the bottom of the file and find the dependencies.

I'll close this as there isn't so much actionable here, if there's any order you think should change, feel free to raise a PR and we can discuss that specific change further.
