### ISSUE TITLE
--lint / --check mode

### ISSUE THREAD

**Issue by kachkaev** [keithamus/sort-package-json#67]
This is a great tool, I'm really glad that I've found it! 🙌

As a maintainer of a monorepo, I would like to use `sort-package-json` in PR pipelines to prevent unsorted `package.json` files from landing the `master` branch. Basically I'd like the tool to become a part of the linting task alongside `eslint`,  `tsc` and `prettier`. Would it be possible to add a new option called `--lint` or `--check`, which instead of writing the files would make `sort-package-json` just return a non-zero exit code if there is a diff?

I know that I can already set a pre-commit hook, but it can be skipped by a contributor. It is also possible to run `sort-package-json` in CI ‘normally’ and then check the git diff, but that's a bit laborious. Here's what looks to me as an decent solution (note `lint:package-json`):

```json
{
  "scripts": {
    "fix": "yarn fix:package-json && yarn fix:prettier",
    "fix:package-json": "sort-package-json package.json packages/*/package.json",
    "fix:prettier": "prettier --write \"**/*.*\"",
    "lint": "yarn lint:package-json && yarn lint:prettier && lint:tsc",
    "lint:package-json": "sort-package-json --check package.json packages/*/package.json",
    "lint:prettier": "prettier --check \"**/*.*\"",
    "lint:tsc": "yarn workspaces run lint:tsc",
  }
}
```

See [Prettier's `--check`](https://prettier.io/docs/en/cli.html#check) as an inspiration.

**Comment by dosentmatter** [comment]
If you are up for it, you can just use the [API](https://github.com/keithamus/sort-package-json/blob/de04f882fc88434f4895788e22ed63531a05c053/index.js#L200-L202).

It only overwrites files if you [run it on the CLI](https://github.com/keithamus/sort-package-json/blob/de04f882fc88434f4895788e22ed63531a05c053/index.js#L204-L218).

From reading the code, you can pass either a string or object to `sortPackageJson()` and it will return back the same type as you gave it. On the CLI, the code depends on [string comparison](https://github.com/keithamus/sort-package-json/blob/de04f882fc88434f4895788e22ed63531a05c053/index.js#L214) to check if sorting was done.

If you pass `sortPackageJson()` an object, it will return a new object, so you can't really use that to check if sorting was done, since they are different references.

First thing, a note. You may be wondering how an object can have sorted keys. Isn't order not guaranteed in a javascript object? Shouldn't the code be using `Map()`? If you look `sort-object-keys`, a package that this depends on, you can see that it just returns a [new object with keys inserted in a sorted order](https://github.com/keithamus/sort-object-keys/blob/master/index.js#L10-L13). Well in [ES6, objects keys are actually sorted by insertion order](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/). Most [major browsers already sorted before ES6](https://stackoverflow.com/a/23202095/7381355). [Relevant spec](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys). In general, I wouldn't rely on it everywhere.

So if you get back an object, you would have to write your own logic to check if sorting was done.

Or you can just do the lazy way, and rely on the sorted keys thing I mentioned above:
```js
JSON.stringify(sortedObj) === JSON.stringify(originalObj)
```

Or you can just pass in a string into `sortPackageJson()` instead of an object.

**Comment by kachkaev** [comment]
I think I found a perfect solution by using [`prettier-plugin-packagejson`](https://github.com/matzkoh/prettier-plugin-packagejson), which works on top of `sort-package-json`.

```bash
yarn add --dev prettier prettier-plugin-packagejson

yarn prettier --check package.json
yarn prettier --write package.json
```
Of course, with [Prettier](https://prettier.io/)'s API it is possible to do much more than just checking or formatting package.json. All my source files are always handled by it. `sort-package-json` was a great discovery for me and I'm glad I could leverage it without making my `package.json` more complicated! 🎉

**Comment by fisker** [comment]
I was going to open a feature request, but found this issue, I think we should support this, we already has cli, why relay on prettier.

solutions:

1.  default to lint, requires flag to fix, `--fix`(eslint use this flag)  or `--write`(prettier use this flag)

```bash
sort-package-json package.json

sort-package-json package.json --fix
```

2. default to fix, requires flag to check `--check`(prettier use this flag) or `--lint`(@kachkaev proposed)

```bash

sort-package-json package.json --check

sort-package-json package.json
```

I can accept any these solutions, also I can help implement.

@keithamus

**Comment by keithamus** [comment]
I'd be happy to add a `--check` option 👍

I'd like to avoid serious breaking changes if we can. Making `--fix` opt in is a substantial breaking change.
